name: DungeonsXL
version: 1.8.3-R0.1
main: com.dre.dungeonsxl.P
authors: [Frank Baumann]
softdepend: [Vault]
commands:
  dungeonsxl:
    description: Reference command for DungeonsXL.
    aliases: [dxl,dungeon]
